### model
model_name_or_path: EleutherAI/llemma_7b
#model_name_or_path: Qwen/Qwen2.5-Coder-7B
#model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 32
lora_target: all

### dataset
dataset: std_spec_RQ1
#template: llama3
#template: qwen
cutoff_len: 2048
max_samples: 500000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /projects/bdkg/jhu11/saves/llemma-7b-3epoch-r32-e4-RQ1/lora/sft
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
#report_to: wandb

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
#eval_dataset: std_premises_evaluation_with_pre_label
val_size: 0.05
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 250
