### model
model_name_or_path: Qwen/Qwen2.5-Coder-7B
reward_model: /projects/bdkg/jhu11/saves/qwen2.5-coder-7b-ppo/lora/reward
trust_remote_code: true

### method
stage: ppo
do_train: true
finetuning_type: lora
lora_rank: 32
lora_target: all

### dataset
dataset: std_premises
template: qwen
cutoff_len: 2048
max_samples: 50000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /projects/bdkg/jhu11/saves/qwen2.5-coder-7b-ppo/lora/ppo
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### generate
max_new_tokens: 512
top_k: 0
top_p: 0.9
